---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(processName)-10s - %(process)d %(name)s - %(levelname)s - %(funcName)s - %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: simulator.log
        maxBytes: 1048576
        backupCount: 5
root:
    level: INFO
    #handlers: [console, file_handler]
    handlers: [file_handler]